version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
  ignore:
  - dependency-name: "jsonschema"
    update-types: ["version-update:semver-major"]
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
