# PyUp config
# https://pyup.io/docs/bot/config/
# Check dependencies in _only_ requirements-app, and open PRs with PyUp prefix.

search: False
schedule: "every week on sunday"

requirements:

  - requirements.in:
      update: all
      pin: True

  - requirements-dev.in:
      update: False
      pin: False

  - requirements.txt:
      update: False

  - requirements-dev.txt:
      update: False

pr_prefix: "PyUp - "
