"""add obscured id column

Revision ID: 1050
Revises: 1040
Create Date: 2017-11-14 11:23:55.612403

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1050'
down_revision = '1040'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_award_projects', sa.Column('obscured_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_award_projects', 'obscured_id')
    # ### end Alembic commands ###

