"""empty message

Revision ID: 54332d69bedb
Revises: 3d5aabf7d291
Create Date: 2015-04-21 07:45:29.958447

"""

# revision identifiers, used by Alembic.
revision = '10_adding_supplier_to_user_table'
down_revision = '3d5aabf7d291'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('supplier_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_users_supplier_id'), 'users', ['supplier_id'], unique=False)
    op.create_foreign_key(None, 'users', 'suppliers', ['supplier_id'], ['supplier_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_supplier_id'), table_name='users')
    op.drop_column('users', 'supplier_id')
    ### end Alembic commands ###
