"""empty message

Revision ID: 2d2309ce61f
Revises: 110_add_acknowledged_column
Create Date: 2015-06-17 11:40:51.427138

"""

# revision identifiers, used by Alembic.
revision = '110_add_acknowledged_column'
down_revision = '100_add_open_status'

from alembic import op
import sqlalchemy as sa

from sqlalchemy.sql import column, table
from sqlalchemy import Boolean


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_events', sa.Column('acknowledged', sa.Boolean(), nullable=True))
    op.add_column('audit_events', sa.Column('acknowledged_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_events_acknowledged'), 'audit_events', ['acknowledged'], unique=False)

    audit_events = table('audit_events', column('acknowledged', Boolean))

    op.execute(
        audit_events.update(). \
        values({'acknowledged': op.inline_literal(False)})
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_events_acknowledged'), table_name='audit_events')
    op.drop_column('audit_events', 'acknowledged_by')
    op.drop_column('audit_events', 'acknowledged')
    ### end Alembic commands ###
