"""Add framework application

Revision ID: 110_add_framework_applications
Revises: 100_add_open_status
Create Date: 2015-06-19 16:22:21.510509

"""

# revision identifiers, used by Alembic.
revision = '110_add_framework_applications'
down_revision = '100_add_open_status'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework_applications',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'framework_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework_applications')
    ### end Alembic commands ###
