"""add framework lifecycle dates

Revision ID: 1140
Revises: 1130
Create Date: 2018-04-24 16:12:57.035498

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1140'
down_revision = '1130'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frameworks', sa.Column('applications_close_at_utc', sa.DateTime(), nullable=True))
    op.add_column('frameworks', sa.Column('clarifications_close_at_utc', sa.DateTime(), nullable=True))
    op.add_column('frameworks', sa.Column('clarifications_publish_at_utc', sa.DateTime(), nullable=True))
    op.add_column('frameworks', sa.Column('framework_expires_at_utc', sa.DateTime(), nullable=True))
    op.add_column('frameworks', sa.Column('framework_live_at_utc', sa.DateTime(), nullable=True))
    op.add_column('frameworks', sa.Column('intention_to_award_at_utc', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frameworks', 'intention_to_award_at_utc')
    op.drop_column('frameworks', 'framework_live_at_utc')
    op.drop_column('frameworks', 'framework_expires_at_utc')
    op.drop_column('frameworks', 'clarifications_publish_at_utc')
    op.drop_column('frameworks', 'clarifications_close_at_utc')
    op.drop_column('frameworks', 'applications_close_at_utc')
    # ### end Alembic commands ###

