"""Remove deprecated application_close_date field and set the remaining date fields to non-nullable.

Revision ID: 1160
Revises: 1150
Create Date: 2018-05-08 09:53:43.699711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import table, column, and_

# revision identifiers, used by Alembic.
revision = '1160'
down_revision = '1150'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('frameworks', 'applications_close_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('frameworks', 'clarifications_close_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('frameworks', 'clarifications_publish_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('frameworks', 'framework_expires_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('frameworks', 'framework_live_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.alter_column('frameworks', 'intention_to_award_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=False)
    op.drop_column('frameworks', 'application_close_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frameworks',
                  sa.Column('application_close_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('frameworks', 'intention_to_award_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('frameworks', 'framework_live_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('frameworks', 'framework_expires_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('frameworks', 'clarifications_publish_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('frameworks', 'clarifications_close_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    op.alter_column('frameworks', 'applications_close_at_utc',
                    existing_type=postgresql.TIMESTAMP(),
                    nullable=True)
    # ### end Alembic commands ###

