"""Insert framework components for direct award and further competition

Revision ID: 1190
Revises: 1180
Create Date: 2018-05-17 14:29:49.989188

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1190'
down_revision = '1180'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frameworks', sa.Column('has_direct_award', sa.Boolean(), nullable=True))
    op.add_column('frameworks', sa.Column('has_further_competition', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frameworks', 'has_further_competition')
    op.drop_column('frameworks', 'has_direct_award')
    # ### end Alembic commands ###

