"""add company_details_confirmed to supplier framework

Revision ID: 1240
Revises: 1230
Create Date: 2018-06-19 15:26:36.055126

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1240'
down_revision = '1230'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_frameworks', sa.Column('application_company_details_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_frameworks', 'application_company_details_confirmed')
    # ### end Alembic commands ###

