"""Add new 'ready to assess' column, for the slightly unusual single-button "Confirm you have read and understood how
to assess services" interaction.

Revision ID: 1250
Revises: 1240
Create Date: 2018-07-02 14:55:09.228538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1250'
down_revision = '1240'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_award_projects', sa.Column('ready_to_assess_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_award_projects', 'ready_to_assess_at')
    # ### end Alembic commands ###

