"""empty message

Revision ID: 12e3e673a7b
Revises: 178754d7108a
Create Date: 2015-03-09 17:10:06.096129

"""

# revision identifiers, used by Alembic.
revision = '12e3e673a7b'
down_revision = '178754d7108a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'updated_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'updated_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('services', 'updated_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
