"""empty message

Revision ID: 12f9dcc2e36c
Revises: 12e3e673a7b
Create Date: 2015-03-11 17:24:26.208655

"""

# revision identifiers, used by Alembic.
revision = '12f9dcc2e36c'
down_revision = '12e3e673a7b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('archived_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_reason', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archived_services_service_id'), 'archived_services', ['service_id'], unique=False)
    op.create_index(op.f('ix_archived_services_supplier_id'), 'archived_services', ['supplier_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_archived_services_supplier_id'), table_name='archived_services')
    op.drop_index(op.f('ix_archived_services_service_id'), table_name='archived_services')
    op.drop_table('archived_services')
    ### end Alembic commands ###
