"""Use unique constraints instead of unique indices

Revision ID: 1350
Revises: 1340
Create Date: 2019-07-10 12:43:28.461996

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1350'
down_revision = '1340'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_direct_award_projects_external_id'), 'direct_award_projects', ['external_id'])
    op.drop_index('ix_direct_award_projects_external_id', table_name='direct_award_projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_direct_award_projects_external_id', 'direct_award_projects', ['external_id'], unique=True)
    op.drop_constraint(op.f('uq_direct_award_projects_external_id'), 'direct_award_projects', type_='unique')
    # ### end Alembic commands ###

