"""Use unique constraints instead of unique indices on services table

Revision ID: 1360
Revises: 1350
Create Date: 2019-07-10 12:43:28.461996

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1360'
down_revision = '1350'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_services_service_id'), 'services', ['service_id'])
    op.drop_index('ix_services_service_id', table_name='services')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_services_service_id', 'services', ['service_id'], unique=True)
    op.drop_constraint(op.f('uq_services_service_id'), 'services', type_='unique')
    # ### end Alembic commands ###

