"""Use unique constraints instead of unique indices on Supplier.duns_number

Revision ID: 1370
Revises: 1360
Create Date: 2019-07-10 12:43:28.461996

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1370'
down_revision = '1360'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_suppliers_duns_number'), 'suppliers', ['duns_number'])
    op.drop_index('ix_suppliers_duns_number', table_name='suppliers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_suppliers_duns_number', 'suppliers', ['duns_number'], unique=True)
    op.drop_constraint(op.f('uq_suppliers_duns_number'), 'suppliers', type_='unique')
    # ### end Alembic commands ###

