"""Use unique constraints instead of unique indices on User.email_address

Revision ID: 1380
Revises: 1370
Create Date: 2019-07-10 12:43:28.461996

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '1380'
down_revision = '1370'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email_address'), 'users', ['email_address'])
    op.drop_index('ix_users_email_address', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_email_address', 'users', ['email_address'], unique=True)
    op.drop_constraint(op.f('uq_users_email_address'), 'users', type_='unique')
    # ### end Alembic commands ###

