"""Add selection answers

Revision ID: 150_add_selection_answers
Revises: 140_service_id_null_for_drafts
Create Date: 2015-06-19 16:22:21.510509

"""

# revision identifiers, used by Alembic.
revision = '150_add_selection_answers'
down_revision = '140_service_id_null_for_drafts'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection_answers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('framework_id', sa.Integer(), nullable=False),
    sa.Column('question_answers', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['framework_id'], ['frameworks.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'framework_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_answers')
    ### end Alembic commands ###
