"""empty message

Revision ID: 178762dff445
Revises: 12f9dcc2e36c
Create Date: 2015-03-26 11:02:49.934915

"""

# revision identifiers, used by Alembic.
revision = '178762dff445'
down_revision = '12f9dcc2e36c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frameworks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('frameworks')
    ### end Alembic commands ###
