"""empty message

Revision ID: 178754d7108a
Revises: 21eb9b29c651
Create Date: 2015-03-09 17:04:22.389566

"""

# revision identifiers, used by Alembic.
revision = '178754d7108a'
down_revision = '21eb9b29c651'

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('services', sa.Column('updated_reason', sa.String(), nullable=True))

    services = table('services',
                     column('updated_by', String),
                     column('updated_reason', String)
    )

    op.execute(
        services.update(). \
        values({'updated_by': op.inline_literal('import'), 'updated_reason': op.inline_literal('initial import')})
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'updated_reason')
    op.drop_column('services', 'updated_by')
    ### end Alembic commands ###
