"""empty message

Revision ID: dc928532835
Revises: 180_remove_user_locked_flag
Create Date: 2015-08-05 11:28:39.205686

"""

# revision identifiers, used by Alembic.
revision = '190_add_companies_house_number'
down_revision = '180_remove_user_locked_flag'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('companies_house_number', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'companies_house_number')
    ### end Alembic commands ###
