"""empty message

Revision ID: 1e74a2d74d2d
Revises: c8bce0740af
Create Date: 2015-02-12 14:02:10.416334

"""

# revision identifiers, used by Alembic.
revision = '1e74a2d74d2d'
down_revision = 'c8bce0740af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address1', sa.String(length=255), nullable=True),
    sa.Column('address2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=255), nullable=True),
    sa.Column('company_number', sa.String(length=255), nullable=True),
    sa.Column('duns_number', sa.String(length=255), nullable=True),
    sa.Column('vat_number', sa.String(length=255), nullable=True),
    sa.Column('vendor_id', sa.String(length=255), nullable=True),
    sa.Column('esourcing_id', sa.String(length=255), nullable=True),
    sa.Column('url_key', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=5000), nullable=True),
    sa.Column('clients_string', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('suppliers')
    ### end Alembic commands ###
