"""empty message

Revision ID: 324d95b19e9c
Revises: 200_new_supplier_id_seq
Create Date: 2015-08-09 09:27:05.848655

"""

# revision identifiers, used by Alembic.
revision = '210_allow_null_postcodes'
down_revision = '200_new_supplier_id_seq'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_information', 'postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_information', 'postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###
