"""empty message

Revision ID: 230_index_duns_number
Revises: 220_rename_companies_house_id
Create Date: 2015-08-12 12:54:36.594852

"""

# revision identifiers, used by Alembic.
revision = '230_index_duns_number'
down_revision = '220_rename_companies_house_id'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_suppliers_duns_number'), 'suppliers', ['duns_number'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppliers_duns_number'), table_name='suppliers')
    ### end Alembic commands ###
