"""empty message

Revision ID: 2eb6ff9b2c1c
Revises: 8354e1a5b85
Create Date: 2015-03-09 18:26:28.634979

"""

# revision identifiers, used by Alembic.
revision = '2eb6ff9b2c1c'
down_revision = '8354e1a5b85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_services_archive_service_id', table_name='services_archive')
    op.create_index(op.f('ix_services_archive_service_id'), 'services_archive', ['service_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_archive_service_id'), table_name='services_archive')
    op.create_index('ix_services_archive_service_id', 'services_archive', ['service_id'], unique=True)
    ### end Alembic commands ###
