"""

Revision ID: 30_add_versioning_to_suppliers
Revises: 20_adding_json_index_to_services
Create Date: 2015-05-29 12:09:45.367765

"""

# revision identifiers, used by Alembic.
revision = '30_add_versioning_to_suppliers'
down_revision = '20_adding_json_index_to_services'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(), autoincrement=False, nullable=True),
    sa.Column('duns_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('esourcing_id', sa.String(), autoincrement=False, nullable=True),
    sa.Column('clients', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_suppliers_version_end_transaction_id'), 'suppliers_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_suppliers_version_operation_type'), 'suppliers_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_suppliers_version_supplier_id'), 'suppliers_version', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_suppliers_version_transaction_id'), 'suppliers_version', ['transaction_id'], unique=False)
    op.create_table('contact_information_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('supplier_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('contact_name', sa.String(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.String(), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(), autoincrement=False, nullable=True),
    sa.Column('website', sa.String(), autoincrement=False, nullable=True),
    sa.Column('address1', sa.String(), autoincrement=False, nullable=True),
    sa.Column('address2', sa.String(), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(), autoincrement=False, nullable=True),
    sa.Column('country', sa.String(), autoincrement=False, nullable=True),
    sa.Column('postcode', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_contact_information_version_end_transaction_id'), 'contact_information_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_contact_information_version_operation_type'), 'contact_information_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_contact_information_version_transaction_id'), 'contact_information_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_contact_information_version_transaction_id'), table_name='contact_information_version')
    op.drop_index(op.f('ix_contact_information_version_operation_type'), table_name='contact_information_version')
    op.drop_index(op.f('ix_contact_information_version_end_transaction_id'), table_name='contact_information_version')
    op.drop_table('contact_information_version')
    op.drop_index(op.f('ix_suppliers_version_transaction_id'), table_name='suppliers_version')
    op.drop_index(op.f('ix_suppliers_version_supplier_id'), table_name='suppliers_version')
    op.drop_index(op.f('ix_suppliers_version_operation_type'), table_name='suppliers_version')
    op.drop_index(op.f('ix_suppliers_version_end_transaction_id'), table_name='suppliers_version')
    op.drop_table('suppliers_version')
    ### end Alembic commands ###
