"""Add timestamp for when framework agreement was returned

Revision ID: 390_agreement_returned_at
Revises: 380_add_supplierframework
Create Date: 2015-11-03 15:20:31.111863

"""

# revision identifiers, used by Alembic.
revision = '390_agreement_returned_at'
down_revision = '380_add_supplierframework'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_frameworks', sa.Column('agreement_returned_at', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_frameworks', 'agreement_returned_at')
    ### end Alembic commands ###
