"""empty message

Revision ID: 3acf60608a7d
Revises: 48a5caa0a762
Create Date: 2015-03-26 11:26:40.461247

"""

# revision identifiers, used by Alembic.
revision = '3acf60608a7d'
down_revision = '48a5caa0a762'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archived_services', 'framework_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('services', 'framework_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'framework_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('archived_services', 'framework_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    ### end Alembic commands ###
