"""empty message

Revision ID: 3d3fb04d1a98
Revises: 597e346723ee
Create Date: 2015-03-25 17:02:16.595140

"""

# revision identifiers, used by Alembic.
revision = '3d3fb04d1a98'
down_revision = '597e346723ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archived_services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('archived_services', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
