"""empty message

Revision ID: 400_drop_agreement_returned
Revises: 390_agreement_returned_at
Create Date: 2015-11-06 10:21:40.412253

"""

# revision identifiers, used by Alembic.
revision = '400_drop_agreement_returned'
down_revision = '390_agreement_returned_at'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier_frameworks', 'agreement_returned')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier_frameworks', sa.Column('agreement_returned', sa.BOOLEAN(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
