"""empty message

Revision ID: 427bdc69b94f
Revises: 550715127385
Create Date: 2015-04-14 14:28:39.295184

"""

# revision identifiers, used by Alembic.
revision = '427bdc69b94f'
down_revision = '550715127385'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact_information', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('contact_information', 'postcode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('suppliers', sa.Column('description', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'description')
    op.alter_column('contact_information', 'postcode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('contact_information', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    ### end Alembic commands ###
