"""empty message

Revision ID: 44a419a59a04
Revises: 12f9dcc2e36c
Create Date: 2015-03-26 10:53:47.473203

"""

# revision identifiers, used by Alembic.
revision = '44a419a59a04'
down_revision = '12f9dcc2e36c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('framework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expired', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('framework')
    ### end Alembic commands ###
