"""empty message

Revision ID: 44b66d53c52
Revises: 427bdc69b94f
Create Date: 2015-04-17 11:05:16.790750

"""

# revision identifiers, used by Alembic.
revision = '44b66d53c52'
down_revision = '427bdc69b94f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'suppliers_duns_number_key', 'suppliers', type_='unique')
    op.drop_constraint(u'suppliers_esourcing_id_key', 'suppliers', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'suppliers_esourcing_id_key', 'suppliers', ['esourcing_id'])
    op.create_unique_constraint(u'suppliers_duns_number_key', 'suppliers', ['duns_number'])
    ### end Alembic commands ###
