"""empty message

Revision ID: 48a5caa0a762
Revises: 178762dff445
Create Date: 2015-03-26 11:25:54.350218

"""

# revision identifiers, used by Alembic.
revision = '48a5caa0a762'
down_revision = '178762dff445'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('archived_services', sa.Column('framework_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_archived_services_framework_id'), 'archived_services', ['framework_id'], unique=False)
    op.create_foreign_key(None, 'archived_services', 'frameworks', ['framework_id'], ['id'])
    op.add_column('services', sa.Column('framework_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_services_framework_id'), 'services', ['framework_id'], unique=False)
    op.create_foreign_key(None, 'services', 'frameworks', ['framework_id'], ['id'])

    op.execute(
        "update archived_services set framework_id = (select id from frameworks where name = 'G-Cloud 6')"
    )

    op.execute(
        "update services set framework_id = (select id from frameworks where name = 'G-Cloud 6')"
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_index(op.f('ix_services_framework_id'), table_name='services')
    op.drop_column('services', 'framework_id')
    op.drop_constraint(None, 'archived_services', type_='foreignkey')
    op.drop_index(op.f('ix_archived_services_framework_id'), table_name='archived_services')
    op.drop_column('archived_services', 'framework_id')
    ### end Alembic commands ###
