"""empty message

Revision ID: 4cb7869866dc
Revises: 8d2b9dcce09
Create Date: 2015-01-20 10:16:42.409106

"""

# revision identifiers, used by Alembic.
revision = '4cb7869866dc'
down_revision = '8d2b9dcce09'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_services_service_id'), 'services', ['service_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_service_id'), table_name='services')
    op.drop_column('services', 'service_id')
    ### end Alembic commands ###
