"""empty message

Revision ID: 56b57f01c4b4
Revises: 12f9dcc2e36c
Create Date: 2015-03-25 11:41:11.390087

"""

# revision identifiers, used by Alembic.
revision = '56b57f01c4b4'
down_revision = '12f9dcc2e36c'

from alembic import op
from sqlalchemy import String


def upgrade():
    op.alter_column('services', 'service_id', type_=String(255))
    op.alter_column('archived_services', 'service_id', type_=String(255))


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
