"""empty message

Revision ID: 5_supplier_cascades
Revises: c8550afd82ec
Create Date: 2016-07-25 11:08:55.994772

"""

# revision identifiers, used by Alembic.
revision = '5_supplier_cascades'
down_revision = 'c8550afd82ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier__service_category')
    op.create_unique_constraint(None, 'price_schedule', ['supplier_id', 'service_role_id'])
    op.drop_constraint(u'price_schedule_supplier_id_fkey', 'price_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'price_schedule', 'supplier', ['supplier_id'], ['id'], ondelete='cascade')
    op.drop_constraint(u'supplier__contact_supplier_id_fkey', 'supplier__contact', type_='foreignkey')
    op.create_foreign_key(None, 'supplier__contact', 'supplier', ['supplier_id'], ['id'], ondelete='cascade')
    op.drop_constraint(u'supplier__extra_links_supplier_id_fkey', 'supplier__extra_links', type_='foreignkey')
    op.create_foreign_key(None, 'supplier__extra_links', 'supplier', ['supplier_id'], ['id'], ondelete='cascade')
    op.drop_constraint(u'supplier_reference_supplier_id_fkey', 'supplier_reference', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_reference', 'supplier', ['supplier_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_reference', type_='foreignkey')
    op.create_foreign_key(u'supplier_reference_supplier_id_fkey', 'supplier_reference', 'supplier', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'supplier__extra_links', type_='foreignkey')
    op.create_foreign_key(u'supplier__extra_links_supplier_id_fkey', 'supplier__extra_links', 'supplier', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'supplier__contact', type_='foreignkey')
    op.create_foreign_key(u'supplier__contact_supplier_id_fkey', 'supplier__contact', 'supplier', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'price_schedule', type_='foreignkey')
    op.create_foreign_key(u'price_schedule_supplier_id_fkey', 'price_schedule', 'supplier', ['supplier_id'], ['id'])
    op.drop_constraint(None, 'price_schedule', type_='unique')
    op.create_table('supplier__service_category',
    sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('service_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['service_category_id'], [u'service_category.id'], name=u'supplier__service_category_service_category_id_fkey'),
    sa.ForeignKeyConstraint(['supplier_id'], [u'supplier.id'], name=u'supplier__service_category_supplier_id_fkey'),
    sa.PrimaryKeyConstraint('supplier_id', 'service_category_id', name=u'supplier__service_category_pkey')
    )
    ### end Alembic commands ###
