"""empty message

Revision ID: 3d5fde6649a8
Revises: 990
Create Date: 2017-10-03 13:39:23.966662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '3d5fde6649a8'
down_revision = '990'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_information', 'country')
    op.drop_column('contact_information', 'address2')
    op.drop_column('contact_information', 'website')
    op.drop_column('suppliers', 'esourcing_id')
    op.drop_column('suppliers', 'clients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('clients', postgresql.JSON(), nullable=True))
    op.add_column('suppliers', sa.Column('esourcing_id', sa.String(), nullable=True))
    op.add_column('contact_information', sa.Column('website', sa.String(), nullable=True),
    op.add_column('contact_information', sa.Column('address2', sa.String(), nullable=True),
    op.add_column('contact_information', sa.Column('country', sa.String(), nullable=True)
    # ### end Alembic commands ###

