"""empty message

Revision ID: 130db5101c2b
Revises: 60_add_acknowledged_column
Create Date: 2015-06-17 11:44:15.535439

"""

# revision identifiers, used by Alembic.
revision = '70_acknowledged_not_null'
down_revision = '60_add_acknowledged_column'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_events', 'acknowledged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###
