"""Add table for managing supplier account invitations

Revision ID: 720_supplier_invite
Revises: 710
Create Date: 2016-08-22 14:25:08.193124

"""

# revision identifiers, used by Alembic.
revision = '720_supplier_invite'
down_revision = '710'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_user_invite_log',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('invite_sent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('supplier_id', 'contact_id')
    )
    op.create_index(op.f('ix_supplier_user_invite_log_invite_sent'), 'supplier_user_invite_log', ['invite_sent'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_user_invite_log_invite_sent'), table_name='supplier_user_invite_log')
    op.drop_table('supplier_user_invite_log')
    ### end Alembic commands ###
