"""Update migrations

Revision ID: 730
Revises: 720_supplier_invite
Create Date: 2016-09-06 11:31:51.026480

"""

# revision identifiers, used by Alembic.
revision = '730'
down_revision = '720_supplier_invite'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_brief_withdrawn_at'), 'brief', ['withdrawn_at'], unique=False)
    op.drop_index('ix_briefs_withdrawn_at', table_name='brief')
    op.create_foreign_key(None, 'supplier_user_invite_log', 'supplier__contact', ['supplier_id', 'contact_id'], ['supplier_id', 'contact_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier_user_invite_log', type_='foreignkey')
    op.create_index('ix_briefs_withdrawn_at', 'brief', ['withdrawn_at'], unique=False)
    op.drop_index(op.f('ix_brief_withdrawn_at'), table_name='brief')
    ### end Alembic commands ###
