"""add work order

Revision ID: d000168043ce
Revises: 740
Create Date: 2016-09-21 10:44:55.461326

"""

# revision identifiers, used by Alembic.
revision = '750'
down_revision = '740'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['brief.id'], ),
    sa.ForeignKeyConstraint(['supplier_code'], ['supplier.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_created_at'), 'work_order', ['created_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_order_created_at'), table_name='work_order')
    op.drop_table('work_order')
    ### end Alembic commands ###
