"""work order unique constraint

Revision ID: 632a37a3efc8
Revises: 760
Create Date: 2016-09-23 09:50:35.236916

"""

# revision identifiers, used by Alembic.
revision = '770'
down_revision = '760'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'work_order', ['brief_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_order', type_='unique')
    ### end Alembic commands ###
