"""empty message

Revision ID: 790
Revises: 780
Create Date: 2016-10-11 15:18:01.489695

"""

# revision identifiers, used by Alembic.
revision = '790'
down_revision = '780'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_study',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=False),
    sa.Column('supplier_code', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_code'], ['supplier.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_study_created_at'), 'case_study', ['created_at'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_study_created_at'), table_name='case_study')
    op.drop_table('case_study')
    ### end Alembic commands ###
