"""empty message

Revision ID: 7_sr_abbreviations_not_null
Revises: 6_service_role_abbreviations
Create Date: 2016-07-25 12:13:20.172782

"""

# revision identifiers, used by Alembic.
revision = '7_sr_abbreviations_not_null'
down_revision = '6_service_role_abbreviations'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_category', 'abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('service_role', 'abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service_role', 'abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('service_category', 'abbreviation',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    ### end Alembic commands ###
