"""Disallow NULLs in certain JSON fields"""

# revision identifiers, used by Alembic.
revision = '810'
down_revision = '800'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('archived_services', 'data',
               existing_type=postgresql.JSON,
               nullable=False)
    op.alter_column('briefs', 'data',
               existing_type=postgresql.JSON,
               nullable=False)
    op.alter_column('draft_services', 'data',
               existing_type=postgresql.JSON,
               nullable=False)
    op.alter_column('services', 'data',
               existing_type=postgresql.JSON,
               nullable=False)
    op.alter_column('suppliers', 'clients',
               existing_type=postgresql.JSON,
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'clients',
               existing_type=postgresql.JSON,
               nullable=True)
    op.alter_column('services', 'data',
               existing_type=postgresql.JSON,
               nullable=True)
    op.alter_column('draft_services', 'data',
               existing_type=postgresql.JSON,
               nullable=True)
    op.alter_column('briefs', 'data',
               existing_type=postgresql.JSON,
               nullable=True)
    op.alter_column('archived_services', 'data',
               existing_type=postgresql.JSON,
               nullable=True)
    # ### end Alembic commands ###
