""" Add application table and applicant user role

Revision ID: 810
Revises: 800
Create Date: 2016-10-11 15:18:01.489695

"""

# revision identifiers, used by Alembic.
revision = '810'
down_revision = '800'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_created_at'), 'application', ['created_at'], unique=False)
    op.execute("ALTER TYPE user_roles_enum ADD value 'applicant';")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_created_at'), table_name='application')
    op.drop_table('application')
    ### end Alembic commands ###
