"""empty message

Revision ID: 8354e1a5b85
Revises: 12e3e673a7b
Create Date: 2015-03-09 17:31:18.082121

"""

# revision identifiers, used by Alembic.
revision = '8354e1a5b85'
down_revision = '12e3e673a7b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.BigInteger(), nullable=False),
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_reason', sa.String(), nullable=False),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.supplier_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_archive_service_id'), 'services_archive', ['service_id'], unique=True)
    op.create_index(op.f('ix_services_archive_supplier_id'), 'services_archive', ['supplier_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_archive_supplier_id'), table_name='services_archive')
    op.drop_index(op.f('ix_services_archive_service_id'), table_name='services_archive')
    op.drop_table('services_archive')
    ### end Alembic commands ###
