"""New domains

Revision ID: 840
Revises: 830
Create Date: 2016-12-05 11:15:34.824623

"""

# revision identifiers, used by Alembic.
revision = '840'
down_revision = '830'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

import yaml
domainlist = yaml.load(open('data/domains.yaml'))


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_domain',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('assessed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'domain_id')
    )

    op.create_index(op.f('ix_application_status'), 'application', ['status'], unique=False)
    op.create_foreign_key(None, 'application', 'supplier', ['supplier_code'], ['code'])
    ### end Alembic commands ###

    conn = op.get_bind()

    for d in domainlist:
        conn.execute(text("""
            insert into
                domain (name)
            values
                (:domain);
        """), domain=d)

    op.execute('alter sequence supplier_code_seq restart with 311;')

    op.execute("""
        alter table "public"."application" alter column "status" set not null;

        alter table "public"."application" alter column "status" set data type application_status_enum using status::application_status_enum;

        alter table "public"."supplier" alter column "status" set not null;

        alter table "public"."supplier" alter column "status" set data type supplier_status_enum using status::supplier_status_enum;
    """)

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_index(op.f('ix_application_status'), table_name='application')

    op.drop_table('supplier_domain')
    op.drop_table('domain')
    ### end Alembic commands ###
