"""user application

Revision ID: b48fd3ae3d00
Revises: 840
Create Date: 2016-12-15 14:17:27.554023

"""

# revision identifiers, used by Alembic.
revision = '850'
down_revision = '840'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'application_user_id_fkey', 'application', type_='foreignkey')
    op.add_column('user', sa.Column('application_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_user_application_id'), 'user', ['application_id'], unique=False)
    op.create_foreign_key(None, 'user', 'application', ['application_id'], ['id'], ondelete='cascade')
    op.execute("""
        update "user" u set application_id = a.id from application a where a.user_id = u.id;
    """)
    op.drop_column('application', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_application_id'), table_name='user')
    op.drop_column('user', 'application_id')
    op.add_column('application', sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'application_user_id_fkey', 'application', 'user', ['user_id'], ['id'])
    ### end Alembic commands ###
