"""empty message

Revision ID: 8_supplier_timestamps
Revises: 7_sr_abbreviations_not_null
Create Date: 2016-07-25 14:43:23.630342

"""

# revision identifiers, used by Alembic.
revision = '8_supplier_timestamps'
down_revision = '7_sr_abbreviations_not_null'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('creation_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('supplier', sa.Column('last_update_time', sa.DateTime(timezone=True), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'last_update_time')
    op.drop_column('supplier', 'creation_time')
    ### end Alembic commands ###
