"""signed agreement application

Revision ID: 6fc8a185fadc
Revises: 890
Create Date: 2017-01-18 19:16:21.152443

"""

# revision identifiers, used by Alembic.
revision = '900'
down_revision = '890'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signed_agreement', sa.Column('application_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'signed_agreement', 'application', ['application_id'], ['id'], ondelete='cascade')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'signed_agreement', type_='foreignkey')
    op.drop_column('signed_agreement', 'application_id')
    ### end Alembic commands ###
