"""supplier addresses

Revision ID: 1d2d1b9c9248
Revises: 930
Create Date: 2017-02-16 17:41:00.556561

"""

# revision identifiers, used by Alembic.
revision = '940'
down_revision = '930'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('supplier_code', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'address', 'supplier', ['supplier_code'], ['code'])
    op.execute("""
        update address as a
        set supplier_code = s.code
        from supplier as s
        where s.address_id = a.id;
    """)
    op.drop_constraint(u'supplier_address_id_fkey', 'supplier', type_='foreignkey')
    op.drop_column('supplier', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'supplier_address_id_fkey', 'supplier', 'address', ['address_id'], ['id'])
    op.drop_constraint(None, 'address', type_='foreignkey')
    op.drop_column('address', 'supplier_code')
    # ### end Alembic commands ###
