"""add downloaded_at column to direct award projects

Revision ID: 970
Revises: 960
Create Date: 2017-09-04 09:25:41.968481

"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '970'
down_revision = '960'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('direct_award_projects', sa.Column('downloaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('direct_award_projects', 'downloaded_at')
    # ### end Alembic commands ###

