"""empty message

Revision ID: c8550afd82ec
Revises: d5f1b238105c
Create Date: 2016-07-22 10:54:11.947448

"""

# revision identifiers, used by Alembic.
revision = 'c8550afd82ec'
down_revision = 'd5f1b238105c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier__extra_links',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('website_link_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.ForeignKeyConstraint(['website_link_id'], ['website_link.id'], ),
    sa.PrimaryKeyConstraint('supplier_id', 'website_link_id')
    )
    op.add_column(u'supplier', sa.Column('long_name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'supplier', 'long_name')
    op.drop_table('supplier__extra_links')
    op.drop_table('website_link')
    ### end Alembic commands ###
