ALTER TABLE agency ADD COLUMN whitelisted BOOLEAN NOT NULL DEFAULT true;

INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Accounting Standards Board', 'aasb.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Building and Construction Commission', 'abcc.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Criminal Intelligence Commission', 'acic.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Communications and Media Authority', 'acma.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Charities and Not-for-profits Commission', 'acnc.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Energy Regulator', 'aer.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Fisheries Management Authority', 'afma.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Federal Police', 'afp.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Attorney General''s Department', 'agd.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Airservices Australia', 'airservicesaustralia.com', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Maritime Safety Authority', 'amsa.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Nuclear Science and Technology Organisation', 'ansto.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian National University', 'anu.edu.au', 'Education', 'ACT', false);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Office of Financial Management', 'aofm.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Prudential Regulation Authority', 'apra.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Pesticides and Veterinary Medicines Authority', 'apvma.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Research Council', 'arc.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Renewable Energy Agency', 'arena.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Armadale', 'armadale.wa.gov.au', 'Local', 'WA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Sports Anti-Doping Authority', 'asada.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Securities & Investments Commission', 'asic.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Transport Safety Bureau', 'atsb.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian War Memorial', 'awm.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Ballarat', 'ballarat.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Bayswater', 'bayswater.wa.gov.au', 'Local', 'WA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Blood Authority Australia', 'blood.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Blue Mountains City Council', 'bmcc.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Bundaberg Regional Council', 'bundaberg.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Canterbury-Bankstown', 'cbcity.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Clarence City Council', 'ccc.tas.gov.au', 'Local', 'TAS', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Office of the Commonwealth Director of Public Prosecutions', 'cdpp.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Computer Emergency Response Team', 'cert.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Coordinator-General''s Office', 'cg.tas.gov.au', 'State', 'TAS', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('The City of Charles Sturt', 'charlessturt.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Crown land in New South Wales', 'crownland.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Darwin', 'darwin.nt.gov.au', 'Local', 'NT', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Data61', 'data61.csiro.au', 'Corporate', '', false);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Defence Housing Australia', 'dha.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Department of Primary Industries', 'dpi.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Department of Treasury and Finance', 'dtf.vic.gov.au', 'State', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Office of Environment & Heritage', 'environment.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Eurobodalla Shire Council', 'esc.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Frankston City Council', 'frankston.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Future Fund Management Agency', 'futurefund.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Greater Geelong', 'geelongcity.vic.gov.au', 'Local', 'Vic', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Georges River Council', 'georgesriver.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Glenelg Shire Council', 'glenelg.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Grains Research & Development Corporation', 'grdc.com.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Goldenfields Water County Council', 'gwcc.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Queensland Health', 'health.qld.gov.au', 'State', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Healthdirect Australia', 'healthdirect.org.au', 'Corporate', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Hobsons Bay City Council', 'hobsonsbay.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Department of Home Affairs', 'homeaffairs.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Health Professional Councils Authority', 'hpca.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Australian Human Rights Commission', 'humanrights.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Indigenous Business Australia', 'iba.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Infrastructure NSW', 'infrastructure.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Independent Parliamentary Expenses Authority', 'ipea.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Ipswich City Council', 'ipswich.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Innovation and Science Australia', 'isa.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Department of Jobs and Small Business', 'jobs.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Lake Macquarie City Council', 'lakemac.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Latrobe City Council', 'latrobe.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Level Crossing Removal Authority', 'levelcrossings.vic.gov.au', 'State', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Light Regional Council', 'light.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Livingstone Shire Council', 'livingstone.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Lockyer Valley Regional Council', 'lvrc.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Mid-western Regional Council ', 'midwestern.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Mildura Rural City Council', 'mildura.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Mitchell Shire Council', 'mitchellshire.vic.gov.au', 'Local', 'Vic', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Moira Shire', 'moira.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Moreland City Council', 'moreland.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Moreton Bay Regional Council', 'moretonbay.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Mosman Council', 'mosman.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Archives of Australia', 'naa.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Capital Authority', 'nca.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('The City of Newcastle', 'ncc.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Disability Insurance Agency', 'ndis.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Film and Sound Archive of Australia', 'nfsa.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Gallery of Australia', 'nga.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Industrial Chemicals Notification and Assessment Scheme', 'nicnas.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('National Library of Australia', 'nla.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Northern Beaches Council', 'northernbeaches.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Office of the Australian Information Commissioner', 'oaic.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Office of the Commonwealth Ombudsman', 'ombudsman.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Productivity Commission', 'pc.gov.au', 'Commonwealth', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Department of Planning and Environment', 'planning.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Playford', 'playford.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Port Macquarie-Hastings Council', 'pmhc.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Port Adelaide Enfield', 'portenf.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('City of Prospect', 'prospect.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Public Safety Business Agency', 'psba.qld.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Queensland Government Chief Information Office', 'qgcio.qld.gov.au', 'State', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Randwick City Council', 'randwick.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Redland City Council', 'redland.qld.gov.au', 'Local', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('NSW Rural Fire Service', 'rfs.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Service NSW', 'service.nsw.gov.au', 'State', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Swan Hill Rural City Council', 'swanhill.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('TAFE NSW', 'tafensw.edu.au', 'State', 'NSW', false);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Tourism Australia', 'tourism.australia.com', 'Corporate', '', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Transport Safety Victoria', 'transportsafety.vic.gov.au', 'State', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Queensland Treasury', 'treasury.qld.gov.au', 'State', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Unitywater', 'unitywater.com', 'Enterprise', 'QLD', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('The City of Unley', 'unley.sa.gov.au', 'Local', 'SA', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Waverley Council', 'waverley.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Wellington Shire Council', 'wellington.vic.gov.au', 'Local', 'VIC', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Wollondilly Shire Council', 'wollondilly.nsw.gov.au', 'Local', 'NSW', true);
INSERT INTO agency (name, domain, category, state, whitelisted) VALUES ('Taronga Zoo', 'zoo.nsw.gov.au', 'State', 'NSW', true);

UPDATE agency SET name = 'Australian Aged Care Quality Agency', domain = 'aacqa.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 8;
UPDATE agency SET name = 'Administrative Appeals Tribunal', domain = 'aat.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 3;
UPDATE agency SET name = 'ABC', domain = 'abc.net.au', category = 'Corporate', state = '', whitelisted = true WHERE id = 1;
UPDATE agency SET name = 'Australian Bureau of Statistics', domain = 'abs.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 10;
UPDATE agency SET name = 'Australian Competition & Consumer Commission', domain = 'accc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 12;
UPDATE agency SET name = 'Australian Centre for International Agricultural Research', domain = 'aciar.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 11;
UPDATE agency SET name = 'ACT Government', domain = 'act.gov.au', category = 'State', state = 'ACT', whitelisted = true WHERE id = 2;
UPDATE agency SET name = 'Australian Electoral Commission', domain = 'aec.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 14;
UPDATE agency SET name = 'Australian Financial Security Authority', domain = 'afsa.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 15;
UPDATE agency SET name = 'Attorney-General''s Department', domain = 'ag.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 6;
UPDATE agency SET name = 'Department of Agriculture and Water Resources', domain = 'agriculture.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 36;
UPDATE agency SET name = 'Australian Institute of Aboriginal and Torres Strait Islander Studies', domain = 'aiatsis.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 4;
UPDATE agency SET name = 'Australian Institute of Family Studies', domain = 'aifs.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 16;
UPDATE agency SET name = 'Australian Institute of Health and Welfare', domain = 'aihw.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 103;
UPDATE agency SET name = 'Australian National Audit Office', domain = 'anao.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 17;
UPDATE agency SET name = 'Australia’s National Research Organisation for Women’s Safety', domain = 'anrows.org.au', category = 'Organisation', state = '', whitelisted = true WHERE id = 113;
UPDATE agency SET name = 'Australian Public Service Commission', domain = 'apsc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 18;
UPDATE agency SET name = 'Australian Radiation Protection and Nuclear Safety Agency', domain = 'arpansa.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 19;
UPDATE agency SET name = 'Asbestos Safety and Eradication Agency', domain = 'asbestossafety.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 5;
UPDATE agency SET name = 'Australian Tax Office', domain = 'ato.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 20;
UPDATE agency SET name = 'Audit Office of New South Wales', domain = 'audit.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 70;
UPDATE agency SET name = 'Australian Sports Commission', domain = 'ausport.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 91;
UPDATE agency SET name = 'Australian Transaction Reports and Analysis Centre', domain = 'austrac.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 21;
UPDATE agency SET name = 'Australian Trade and Investment Commission', domain = 'austrade.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 7;
UPDATE agency SET name = 'The Barossa Council', domain = 'barossa.sa.gov.au', category = 'Local', state = 'SA', whitelisted = true WHERE id = 22;
UPDATE agency SET name = 'Bass Coast Shire Council', domain = 'basscoast.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 106;
UPDATE agency SET name = 'Baw Baw Shire Council', domain = 'bawbawshire.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 23;
UPDATE agency SET name = 'Bayside Council', domain = 'bayside.nsw.gov.au', category = 'Local', state = 'NSW', whitelisted = true WHERE id = 104;
UPDATE agency SET name = 'Bureau of Meteorology', domain = 'bom.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 24;
UPDATE agency SET name = 'Australian Border Force', domain = 'border.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 9;
UPDATE agency SET name = 'City of Booroondara', domain = 'boroondara.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 26;
UPDATE agency SET name = 'Byron Shire Council', domain = 'byron.nsw.gov.au', category = 'Local', state = 'NSW', whitelisted = true WHERE id = 107;
UPDATE agency SET name = 'Civil Aviation Safety Authority', domain = 'casa.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 31;
UPDATE agency SET name = 'City of Casey', domain = 'casey.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 27;
UPDATE agency SET name = 'City of Greater Geraldton', domain = 'cgg.wa.gov.au', category = 'Local', state = 'WA', whitelisted = true WHERE id = 28;
UPDATE agency SET name = 'Royal Commission into Institutional Responses to Child Sexual Abuse', domain = 'childabuseroyalcommission.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 25;
UPDATE agency SET name = 'Clean Energy Regulator', domain = 'cleanenergyregulator.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 32;
UPDATE agency SET name = 'Comcare', domain = 'comcare.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 33;
UPDATE agency SET name = 'Department of Communications and the Arts', domain = 'communications.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 37;
UPDATE agency SET name = 'CSIRO', domain = 'csiro.au', category = 'Corporate', state = '', whitelisted = false WHERE id = 34;
UPDATE agency SET name = 'Curtin University', domain = 'curtin.edu.au', category = 'Education', state = 'WA', whitelisted = false WHERE id = 35;
UPDATE agency SET name = 'Department of Defence', domain = 'defence.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 44;
UPDATE agency SET name = 'Department of Environment, Land, Water and Planning', domain = 'delwp.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 38;
UPDATE agency SET name = 'Department of Foreign Affairs and Trade', domain = 'dfat.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 46;
UPDATE agency SET name = 'Digital Transformation Agency', domain = 'digital.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 50;
UPDATE agency SET name = 'Australian Digital Health Agency', domain = 'digitalhealth.gov.au', category = 'Corporate', state = '', whitelisted = true WHERE id = 13;
UPDATE agency SET name = 'Organ and Tissue Authority', domain = 'donatelife.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 61;
UPDATE agency SET name = 'Department of Premier and Cabinet', domain = 'dpc.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 40;
UPDATE agency SET name = 'Department of Science, Information Technology and Innovation', domain = 'dsiti.qld.gov.au', category = 'State', state = 'QLD', whitelisted = true WHERE id = 41;
UPDATE agency SET name = 'Department of Social Services', domain = 'dss.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 49;
UPDATE agency SET name = 'Digital Transformation Agency', domain = 'dta.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 52;
UPDATE agency SET name = 'Digital Transformation Agency', domain = 'dto.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 51;
UPDATE agency SET name = 'Department of Veterans'' Affairs', domain = 'dva.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 43;
UPDATE agency SET name = 'Department of Economic Development, Jobs, Transport and Resources', domain = 'ecodev.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 53;
UPDATE agency SET name = 'Department of Education and Training', domain = 'education.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 45;
UPDATE agency SET name = 'Export Finance and Insurance Corporation', domain = 'efic.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 71;
UPDATE agency SET name = 'Department of Jobs and Small Business', domain = 'employment.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 72;
UPDATE agency SET name = 'Department of the Environment and Energy', domain = 'environment.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 73;
UPDATE agency SET name = 'Department of Finance', domain = 'finance.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 74;
UPDATE agency SET name = 'Department of Finance, Services & Innovation', domain = 'finance.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 75;
UPDATE agency SET name = 'Department of Finance', domain = 'finance.wa.gov.au', category = 'State', state = 'WA', whitelisted = true WHERE id = 67;
UPDATE agency SET name = 'Food Standards Australia New Zealand', domain = 'foodstandards.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 93;
UPDATE agency SET name = 'Fair Work Building and Construction', domain = 'fwbc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 76;
UPDATE agency SET name = 'Fair Work Ombudsman', domain = 'fwo.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 54;
UPDATE agency SET name = 'Geoscience Australia', domain = 'ga.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 77;
UPDATE agency SET name = 'Office of the Government Chief Information Officer', domain = 'gcio.wa.gov.au', category = 'State', state = 'WA', whitelisted = true WHERE id = 96;
UPDATE agency SET name = 'City of Glen Eira', domain = 'gleneira.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 108;
UPDATE agency SET name = 'Department of Health', domain = 'health.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 39;
UPDATE agency SET name = 'NSW Health', domain = 'health.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 78;
UPDATE agency SET name = 'Hepburn Shire Council', domain = 'hepburn.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 109;
UPDATE agency SET name = 'Department of Human Services', domain = 'humanservices.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 47;
UPDATE agency SET name = 'Department of Industry, Innovation and Science', domain = 'industry.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 79;
UPDATE agency SET name = 'Department of Industry', domain = 'industry.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 80;
UPDATE agency SET name = 'Department of Infrastructure, Regional Development and Cities', domain = 'infrastructure.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 81;
UPDATE agency SET name = 'IP Australia', domain = 'ipaustralia.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 55;
UPDATE agency SET name = 'Department of Justice', domain = 'justice.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 82;
UPDATE agency SET name = 'Logan City Council', domain = 'logan.qld.gov.au', category = 'Local', state = 'QLD', whitelisted = true WHERE id = 97;
UPDATE agency SET name = 'Maitland City Council', domain = 'maitland.nsw.gov.au', category = 'Local', state = 'NSW', whitelisted = true WHERE id = 94;
UPDATE agency SET name = 'Municipal Association of Victoria', domain = 'mav.asn.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 56;
UPDATE agency SET name = 'Murray-Darling Basin Authority', domain = 'mdba.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 57;
UPDATE agency SET name = 'City of Melbourne', domain = 'melbourne.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 29;
UPDATE agency SET name = 'Museum of Australian Democracy', domain = 'moadoph.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 83;
UPDATE agency SET name = 'National Health and Medical Research Council', domain = 'nhmrc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 58;
UPDATE agency SET name = 'National Museum of Australia', domain = 'nma.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 92;
UPDATE agency SET name = 'National Native Title Tribunal', domain = 'nntt.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 59;
UPDATE agency SET name = 'National Offshore Petroleum Titles Administrator', domain = 'nopta.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 98;
UPDATE agency SET name = 'Office of National Assessments', domain = 'ona.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 60;
UPDATE agency SET name = 'Office of Parliamentary Counsel', domain = 'opc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 105;
UPDATE agency SET name = 'Department of the Prime Minister and Cabinet', domain = 'pmc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 48;
UPDATE agency SET name = 'Public Service Commission', domain = 'psc.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 99;
UPDATE agency SET name = 'Queensland Building and Construction Commission', domain = 'qbcc.qld.gov.au', category = 'State', state = 'QLD', whitelisted = true WHERE id = 84;
UPDATE agency SET name = 'Queensland Government', domain = 'qld.gov.au', category = 'State', state = 'QLD', whitelisted = true WHERE id = 62;
UPDATE agency SET name = 'Queensland Rural Fire Service', domain = 'rfs.qfes.qld.gov.au', category = 'State', state = 'QLD', whitelisted = true WHERE id = 63;
UPDATE agency SET name = 'VicRoads', domain = 'roads.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 85;
UPDATE agency SET name = 'Government of South Australia', domain = 'sa.gov.au', category = 'State', state = 'SA', whitelisted = true WHERE id = 64;
UPDATE agency SET name = 'Australian Commission on Safety and Quality in Health Care', domain = 'safetyandquality.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 100;
UPDATE agency SET name = 'Service Victoria', domain = 'service.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 86;
UPDATE agency SET name = 'Small Business Commissioner', domain = 'smallbusiness.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 101;
UPDATE agency SET name = 'Service Delivery Office', domain = 'ssc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 87;
UPDATE agency SET name = 'Southern Grampians Shire Council', domain = 'sthgrampians.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 110;
UPDATE agency SET name = 'Tertiary Education Quality and Standards Agency', domain = 'teqsa.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 88;
UPDATE agency SET name = 'Department of Transport and Main Roads', domain = 'tmr.qld.gov.au', category = 'State', state = 'QLD', whitelisted = true WHERE id = 42;
UPDATE agency SET name = 'Tax Practitioners Board', domain = 'tpb.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 112;
UPDATE agency SET name = 'Transport for NSW', domain = 'transport.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 89;
UPDATE agency SET name = 'The Treasury', domain = 'treasury.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 65;
UPDATE agency SET name = 'Department of the Prime Minister and Cabinet', domain = 'unc.pmc.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 111;
UPDATE agency SET name = 'University of New South Wales', domain = 'unsw.edu.au', category = 'Education', state = 'NSW', whitelisted = false WHERE id = 66;
UPDATE agency SET name = 'Town of Victoria Park', domain = 'vicpark.wa.gov.au', category = 'State', state = 'WA', whitelisted = true WHERE id = 90;
UPDATE agency SET name = 'Victorian Managed Insurance Authority', domain = 'vmia.vic.gov.au', category = 'State', state = 'VIC', whitelisted = true WHERE id = 95;
UPDATE agency SET name = 'Workplace Gender Equality Agency', domain = 'wgea.gov.au', category = 'Commonwealth', state = '', whitelisted = true WHERE id = 68;
UPDATE agency SET name = 'Workers Compensation Independent Review Office', domain = 'wiro.nsw.gov.au', category = 'State', state = 'NSW', whitelisted = true WHERE id = 102;
UPDATE agency SET name = 'City of Yarra', domain = 'yarracity.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 30;
UPDATE agency SET name = 'Yarra Ranges Council', domain = 'yarraranges.vic.gov.au', category = 'Local', state = 'VIC', whitelisted = true WHERE id = 69;

ALTER TABLE agency ALTER COLUMN name SET NOT NULL;
