# Dependabot config
# https://dependabot.com/docs/config-file/
# Checks and updates dependencies in
# `requirements.in` and `requirements.txt`

version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    allowed_updates:
      - match:
          dependency_type: "production"
          update_type: "all"
