name: CI

on: [pull_request]

jobs:
  test:
    name: Test against different Python versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6.x, 3.7.x]
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
        architecture: x64
    - name: Install packages and run tests
      run: |
        make requirements-dev
        make test
      env:
        SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@localhost:5432/digitalmarketplace_test