name: Test
on: [pull_request]

jobs:
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9 ]
    # Docker Hub image that `container-job` executes in
    container: python:${{ matrix.python-version }}-buster

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python cache
        uses: actions/cache@v2
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}

      - name: Install packages and run tests
        run: |
          make requirements-dev
          make test
        env:
          SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/postgres
